### ISSUE TITLE
Docker FileNotFoundError: [Errno 2] No such file or directory: '/config/corner_detection.yaml'

### ISSUE THREAD

**Issue by Theawesometurtl** [georgw777/chesscog#20]
Hello, I am a HS student building a chess robot as part of an end-of-the-year project on a raspberry pi. I have limited programming experience. I was running the dockerfile, following instuctions in the github readme, when I ran into this error:

`# python -m chesscog.recognition.recognition image.jpg --white  `

`/usr/local/lib/python3.8/runpy.py:127: RuntimeWarning: 'chesscog.recognition.recognition' found in sys.modules after import of package 'chesscog.recognition', but prior to execution of 'chesscog.recognition.recognition'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[2024-05-31 19:50:21,690] {download.py:80} INFO - Not downloading https://github.com/georg-wolflein/chesscog/releases/download/0.1.0/occupancy_classifier.zip to /chess/models/occupancy_classifier again because it already exists
[2024-05-31 19:50:21,690] {download.py:80} INFO - Not downloading https://github.com/georg-wolflein/chesscog/releases/download/0.1.0/piece_classifier.zip to /chess/models/piece_classifier again because it already exists
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/chess/chesscog/recognition/recognition.py", line 226, in <module>
    main(setup=lambda: [ensure_model(show_size=True)
  File "/chess/chesscog/recognition/recognition.py", line 208, in main
    recognizer = ChessRecognizer(classifiers_folder)
  File "/chess/chesscog/recognition/recognition.py", line 57, in __init__
    self._corner_detection_cfg = CN.load_yaml_with_base(
  File "/usr/local/lib/python3.8/site-packages/recap/config.py", line 44, in load_yaml_with_base
    with uri.open("r") as f:
  File "/usr/local/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/local/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/config/corner_detection.yaml''`

I didn't do anything differing from the readme instruction other than running the following commands to fix some package imports

`apt-get update && apt-get install -y python3-opencv
`

I tried creating a folder named config and copying the corner_detection.yaml file from the github repo, but it still had the same error, possibly the folder I created wasn't in the correct place.

Any help would be appreciated

**Comment by georg-wolflein** [comment]
Can you ensure that you git cloned the whole repository? It seems like you may be missing the config folder: https://github.com/georg-wolflein/chesscog/tree/master/config

On 31. May 2024, at 20:58, Theawesometurtl ***@***.***> wrote:



Hello, I am a HS student building a chess robot as part of an end-of-the-year project on a raspberry pi. I have limited programming experience. I was building the dockerfile, like in the github readme, when I ran into this error:

# python -m chesscog.recognition.recognition image.jpg --white

/usr/local/lib/python3.8/runpy.py:127: RuntimeWarning: 'chesscog.recognition.recognition' found in sys.modules after import of package 'chesscog.recognition', but prior to execution of 'chesscog.recognition.recognition'; this may result in unpredictable behaviour warn(RuntimeWarning(msg)) [2024-05-31 19:50:21,690] {download.py:80} INFO - Not downloading https://github.com/georg-wolflein/chesscog/releases/download/0.1.0/occupancy_classifier.zip to /chess/models/occupancy_classifier again because it already exists [2024-05-31 19:50:21,690] {download.py:80} INFO - Not downloading https://github.com/georg-wolflein/chesscog/releases/download/0.1.0/piece_classifier.zip to /chess/models/piece_classifier again because it already exists Traceback (most recent call last): File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "/chess/chesscog/recognition/recognition.py", line 226, in <module> main(setup=lambda: [ensure_model(show_size=True) File "/chess/chesscog/recognition/recognition.py", line 208, in main recognizer = ChessRecognizer(classifiers_folder) File "/chess/chesscog/recognition/recognition.py", line 57, in __init__ self._corner_detection_cfg = CN.load_yaml_with_base( File "/usr/local/lib/python3.8/site-packages/recap/config.py", line 44, in load_yaml_with_base with uri.open("r") as f: File "/usr/local/lib/python3.8/pathlib.py", line 1222, in open return io.open(self, mode, buffering, encoding, errors, newline, File "/usr/local/lib/python3.8/pathlib.py", line 1078, in _opener return self._accessor.open(self, flags, mode) FileNotFoundError: [Errno 2] No such file or directory: '/config/corner_detection.yaml''

I didn't do anything differing from the readme instruction other than running the following commands to fix some package imports

apt-get update && apt-get install -y python3-opencv

Any help would be appreciated

**Comment by georg-wolflein** [comment]
Can you ensure that you git cloned the whole repository? It seems like you may be missing the config folder: https://github.com/georg-wolflein/chesscog/tree/master/config.

To make sure that chesscog is picking up the correct config directory, please let me know the output of running the following in an interactive python shell:
```python
from chesscog.core.io import _CONFIG_DIR
print(_CONFIG_DIR)
```

**Comment by Theawesometurtl** [comment]
The result of your command was
`/config`

My local github repo seems to be complete, but the docker is missing some folders and files, including the config folder. I've created the docker container multiple times now, and it had the same file structure every time.

Here is an image of the repo clone, and the docker 
![image](https://github.com/georg-wolflein/chesscog/assets/95330177/7104f28f-b4c5-4fb8-b98b-055590afdb29)

![image](https://github.com/georg-wolflein/chesscog/assets/95330177/50fec619-9d0d-46eb-b563-8b200a5ecc66)

**Comment by georg-wolflein** [comment]
Can you start the docker container as follows, and report back?
```bash
PWD=$(pwd)
docker run -it -p 8888:8888 -p 9999:9999 -v $PWD/config:/config -v $PWD/runs:/chess/runs -v $PWD/results:/chess/results -v $PWD/models:/chess/models chesscog
```

(I think I may have forgotten to add the volume mounts in the README instructions...)

**Comment by Theawesometurtl** [comment]
I created a new docker container, ran `$PWD = Get-Location` as a replacement for `PWD=$(pwd)` (since docker should run the same on a different os, I'm building the container on windows first for testing purposes), and ran your docker container command, running into the following errors:

`# python -m chesscog.data_synthesis.download_dataset
python -m chesscog.data_synthesis.split_dataset`
[2024-06-01 16:53:21,031] {download_dataset.py:32} INFO - Extracting val.zip
[2024-06-01 16:53:24,038] {download_dataset.py:32} INFO - Extracting test.zip
[2024-06-01 16:53:29,330] {download_dataset.py:57} INFO - Merging train dataset
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/chess/chesscog/data_synthesis/download_dataset.py", line 59, in <module>
    if os.waitstatus_to_exitcode(os.system(command)) != 0 or not (folder / "train_full.zip").exists():
AttributeError: module 'os' has no attribute 'waitstatus_to_exitcode'
 [2024-06-01 16:53:43,730] {split_dataset.py:31} WARNING - No samples found in 'data://render', either you did not download the datset yet or you have already split it.
0 samples will be split into 0 train, 0 val, 0 test.


`# python -m chesscog.occupancy_classifier.download_model
python -m chesscog.piece_classifier.download_model`
[2024-06-01 17:09:18,202] {download.py:80} INFO - Not downloading https://github.com/georg-wolflein/chesscog/releases/download/0.1.0/occupancy_classifier.zip to /chess/models/occupancy_classifier again because it already exists


`# python -m chesscog.recognition.recognition image.jpg --white  `      
/usr/local/bin/python: No module named chesscog.piece_classifier.download_modelpython

**Comment by georg-wolflein** [comment]
I just tested it myself. Please follow the following instructions and let me know exactly where it fails:

1. Clone the repo
   ```bash
   git clone https://github.com/georg-wolflein/chesscog
   cd chesscog
   ```
2. Build the docker image
   ```bash
   docker build -t chesscog -f cpu.Dockerfile .
   ```
3. Start the container (you can replace `$PWD` with absolute paths if you want)
   ```bash
   PWD=$(pwd); docker run -it --name chesscog -p 8888:8888 -p 9999:9999 -v $PWD/config:/config -v $PWD/runs:/chess/runs -v $PWD/results:/chess/results -v $PWD/models:/chess/models chesscog
   ```
   Leave this terminal window open.
4. In a new terminal window, run the following command
    ```bash
   docker exec -it chesscog /bin/bash
   ```
   This will start a bash shell within the running container. Run the commands below within that shell:
5. Fix opencv dependency
   ```bash
   apt update && apt install -y libgl1-mesa-glx
   ```
6. Download a chess image into the container
   ```bash
   wget -O image.jpg https://i.ebayimg.com/images/g/qbYAAOSwMFFh7i0l/s-l1200.jpg
   ```
7. Run the chess recognition
   ```bash
   python -m chesscog.recognition.recognition image.jpg --white
   ```

This is the output I got from the last step:
```
/usr/local/lib/python3.8/runpy.py:127: RuntimeWarning: 'chesscog.recognition.recognition' found in sys.modules after import of package 'chesscog.recognition', but prior to execution of 'chesscog.recognition.recognition'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[2024-06-01 21:28:25,082] {download.py:51} INFO - Downloading https://github.com/georg-wolflein/chesscog/releases/download/0.1.0/occupancy_classifier.zip to /tmp/tmp40gx4gjf/occupancy_classifier.zip
100%|███████████████████████████████████████████████████████████████████████████████| 41.6M/41.6M [00:00<00:00, 69.6MiB/s]
[2024-06-01 21:28:26,134] {download.py:86} INFO - Unzipping /tmp/tmp40gx4gjf/occupancy_classifier.zip to /chess/models/occupancy_classifier
[2024-06-01 21:28:26,324] {download.py:90} INFO - Finished downloading https://github.com/georg-wolflein/chesscog/releases/download/0.1.0/occupancy_classifier.zip to /chess/models/occupancy_classifier
[2024-06-01 21:28:26,328] {download.py:51} INFO - Downloading https://github.com/georg-wolflein/chesscog/releases/download/0.1.0/piece_classifier.zip to /tmp/tmphes0woq0/piece_classifier.zip
100%|███████████████████████████████████████████████████████████████████████████████| 91.1M/91.1M [00:01<00:00, 57.0MiB/s]
[2024-06-01 21:28:28,584] {download.py:86} INFO - Unzipping /tmp/tmphes0woq0/piece_classifier.zip to /chess/models/piece_classifier
[2024-06-01 21:28:28,993] {download.py:90} INFO - Finished downloading https://github.com/georg-wolflein/chesscog/releases/download/0.1.0/piece_classifier.zip to /chess/models/piece_classifier
. . . . . . . .
. . . . . . . .
. . . R . . . .
n n n N N N n N
. . . . . . . .
. . . . . . . .
r n b q n b r n
. . . . . . . .

You can view this position at https://lichess.org/editor/8/8/3R4/nnnNNNnN/8/8/rnbqnbrn/8

WARNING: The predicted chess position is not legal according to the rules of chess.
         You might want to try again with another picture.
```
(Note that it doesn't correctly identify this chess position, but that is because the system wasn't fine-tuned for that board. The README contains instructions on how to fine-tune the system on your own chessboard.)

**Comment by Theawesometurtl** [comment]
It worked! Thank you! I'm confused on what was wrong with my initial approach, but happy nonetheless
